# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vfl_client_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18vfl_client_service.proto\"a\n\x1flr_train_batch_gradient_request\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x02 \x01(\x05\x12\x16\n\x0e\x62\x61tch_gradient\x18\x03 \x03(\x02\"K\n lr_train_batch_gradient_response\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x14\n\x0creceive_flag\x18\x02 \x01(\x08\x32w\n\x10VFLClientService\x12\x63\n\x1csend_lr_train_batch_gradient\x12 .lr_train_batch_gradient_request\x1a!.lr_train_batch_gradient_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vfl_client_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LR_TRAIN_BATCH_GRADIENT_REQUEST']._serialized_start=28
  _globals['_LR_TRAIN_BATCH_GRADIENT_REQUEST']._serialized_end=125
  _globals['_LR_TRAIN_BATCH_GRADIENT_RESPONSE']._serialized_start=127
  _globals['_LR_TRAIN_BATCH_GRADIENT_RESPONSE']._serialized_end=202
  _globals['_VFLCLIENTSERVICE']._serialized_start=204
  _globals['_VFLCLIENTSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
